//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MydbEntities : DbContext
    {
        public MydbEntities()
            : base("name=MydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<班级> 班级 { get; set; }
        public virtual DbSet<课程> 课程 { get; set; }
        public virtual DbSet<选课> 选课 { get; set; }
        public virtual DbSet<学生> 学生 { get; set; }
        public virtual DbSet<学院> 学院 { get; set; }
    }
}
