//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 学生
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 学生()
        {
            this.选课 = new HashSet<选课>();
        }
    
        public string 学号 { get; set; }
        public string 姓名 { get; set; }
        public string 性别 { get; set; }
        public Nullable<System.DateTime> 出生日期 { get; set; }
        public string 民族 { get; set; }
        public string 地区 { get; set; }
        public string 班级号 { get; set; }
        public string 密码 { get; set; }
    
        public virtual 班级 班级 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<选课> 选课 { get; set; }
    }
}
