//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 课程
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 课程()
        {
            this.选课 = new HashSet<选课>();
        }
    
        public string 课程号 { get; set; }
        public string 课程名称 { get; set; }
        public Nullable<short> 周学时 { get; set; }
        public Nullable<short> 上课周数 { get; set; }
        public Nullable<short> 学分 { get; set; }
        public string 课程简介 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<选课> 选课 { get; set; }
    }
}
