//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 选课
    {
        public string 学期 { get; set; }
        public string 学号 { get; set; }
        public string 课程号 { get; set; }
        public Nullable<short> 成绩 { get; set; }
    
        public virtual 课程 课程 { get; set; }
        public virtual 学生 学生 { get; set; }
    }
}
